### ISSUE TITLE
Provide required headers to fetch data in the test sandbox

### ISSUE THREAD

**Issue by cironunes** [Contiamo/contiamo-client-js#1]

**Comment by micha-f** [comment]
Do you mean access details, i.e. the API key?

**Comment by cironunes** [comment]
Yes. The main issue is about CORS. Maybe you can help me out sometime to get it right.

**Comment by micha-f** [comment]
You need to add the correct `CORS origins` when creating your API key. For testing this would be `localhost:8080`.

**Comment by cironunes** [comment]
aha! Now I feel stupid 😆 .
I'll add it to the README as a development instruction then. WDYT?

**Comment by micha-f** [comment]
Makes sense 👍
